### ISSUE TITLE
No need for global installation

### ISSUE THREAD

**Issue by falk-stefan** [amio/npm-why#153]
Hi!

Thanks for this package. One suggestion though: It's not necessary to install `npm-why` globally. I'd recommend to add something like this to the README.md:

### Install
```
$ npm i npm-why --save-dev
```
### Run 
```
$ $(npm bin)/npm-why @angular/core

  Who required @angular/core:

  my-web-app > @angular/core@11.0.8
```

**Comment by amio** [comment]
@falk-stefan If you don't want to install it globally, `npx` is recommended, it's bundled with npm since 5.2.0: 

```
npx npm-why @angular/core
```

**Comment by falk-stefan** [comment]
Ah, got it. Thanks for the info!
