### ISSUE TITLE
Yarn support?

### ISSUE THREAD

**Issue by nicolo-ribaudo** [amio/npm-why#2]
The output of this package is much more nicer than the yarn output:
```
➜ npx npm-why @babel/helpers
npx: installato 10 in 0.852s

  Who required @babel/helpers:

  babel-upgrade > @babel/core > @babel/helpers@7.0.0-beta.41

➜ yarn why babel-core
yarn why v1.9.4
[1/4] Why do we have the module "babel-core"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "jest-config#babel-core@6.26.0"
info This module exists because "jest#jest-cli#jest-config" depends on it.
info Disk size without dependencies: "228KB"
info Disk size with unique dependencies: "33.28MB"
info Disk size with transitive dependencies: "41.84MB"
info Number of shared dependencies: 40
```

I understand that this package was created specifically for npm because yarn already supported it, but what do you think of supporting both the package managers?

**Comment by amio** [comment]
Glad you like it :D

I'm not sure if it's viable, `yarn.lock` stores less information than `package.json`. I'll check on this later.

BTW, if it‘s viable, I think this feature should be under a new name other than `npm-why` 😄

**Comment by nicolo-ribaudo** [comment]
> BTW, if it‘s viable, I think this feature should be under a new name other than npm-why :smile: 

Well, having them in the same package would be much more handy, so I don't have to ask users to run different commands based on their package manager :slightly_smiling_face: 
e.g. https://github.com/babel/babel/issues/8482#issuecomment-413855035

**Comment by amio** [comment]
I was thinking `why-pkg` (depend on `npm-why` and `yarn-why`) to do the handy job.

**Comment by nicolo-ribaudo** [comment]
It works, thank you! :smile:

**Comment by amio** [comment]
@nicolo-ribaudo and the yarn & npm support are under [`nls`](https://github.com/amio/nls) now: `npx nls why @babel/helpers`.

**Comment by nicolo-ribaudo** [comment]
@amio Thank you again, `npx nls why` is making it a lot easier to help users

**Comment by amio** [comment]
@nicolo-ribaudo Glad to be helpful 😄
