### ISSUE TITLE
Can I analyze all the dependency trees at once?

### ISSUE THREAD

**Issue by brizer** [amio/npm-why#68]
Looked at the current usage, I have to assign the name of the specified package one by one. Can I analyze all the dependency trees at once? For example `npm-why --all`

**Comment by amio** [comment]
Seems you are seeking for `npm ls`?

**Comment by brizer** [comment]
`npm ls` is so simple, I can't intuitively analyze its dependency tree. May be an enhance of it. http://npm.broofa.com/, this is a tool, but can not used in local project. I am try to enhance it for use in local environment.

**Comment by amio** [comment]
http://npm.broofa.com looks cool!

But it seems hard to fits nicely in a terminal window for some project with a lot deps (e.g. http://npm.broofa.com/?q=webpack)

**Comment by brizer** [comment]
Haha, you are right.
